import numpy as np
Crops = np.array(["Wheat", "Rice", "Corn", "Sugarcane"])
rng = np.random.default_rng()
Fields=rng.integers(low=500,high=2001,size=(50,4))
Apc=np.average(Fields,axis=0)
print(Apc)
Max=np.max(Fields,axis=0)
print(Max)
Min=np.min(Fields,axis=0)
print(Min)
Avg=np.average(Fields)
print(Avg)
print(Fields)
sumation=np.sum(Fields,axis=0)
HighestCrop=np.argmax(sumation)
print(Crops[HighestCrop])
LowestCrop=np.argmin(sumation)
print(Crops[LowestCrop])
RiceYield=Fields[Fields[:,1]<1000]
print(RiceYield[:,1])
WheatYield=Fields[Fields[:,0]>1500]
print(WheatYield[:,0])
print(Fields)
NewFields=Fields+np.array([50,40,60,70])
print(NewFields)